### ISSUE TITLE
Hoe & Shovel get destroyed after 1 use

### ISSUE THREAD

**Issue by tartooth** [TheJeterLP/BukkitInventoryTweaks#15]
Start server, make a hoe or shovel, right click on ground and it gets destroyed instantly.

I rolled back to 1.03 but was getting duplication issues, I'm assuming that's what you fixed in 1.04

Sadly, I can't play without the hoe or shovel right click features!

**Comment by TheJeterLP** [comment]
Thanks for pointing out, I'll try to fix that today or tomorrow when I have time :)

**Comment by TheJeterLP** [comment]
Fixed in https://github.com/TheJeterLP/BukkitInventoryTweaks/releases/tag/v1.0.5

**Comment by tartooth** [comment]
Thanks!
