### ISSUE TITLE
Plugin Eating Swords

### ISSUE THREAD

**Issue by NiGel2789** [TheJeterLP/BukkitInventoryTweaks#27]
Hi! We've recently discovered that the plugin eats up one extra sword when replacing a sword on break. An example of this would be:

Player has 2 diamond swords in inventory, and when diamond sword A breaks, the plugin attempts to replace the broken sword, but results in eating diamond sword B, leaving the player with an empty hand.

We're running a vanilla survival Paper server on 1.19.4.

Thank you!

**Comment by TheJeterLP** [comment]
Thanks for your bug report! For now you can remove the swords from the config to prevent item loss until I have fixed this issue. Sadly I can not do that until Tuesday because I am not at home at the moment.

**Comment by NiGel2789** [comment]
Sounds good! Thanks for the prompt response.

**Comment by TheJeterLP** [comment]
Fixed in v1.1.2 :)

**Comment by NiGel2789** [comment]
Thank you!
